#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <latitude> <longitude>"
    exit 1
fi

# Assign the input values to variables
latitude=$1
longitude=$2

# GeoJSON template with placeholders for latitude and longitude
geojson_template='{
    "type": "Point",
    "coordinates": [%s,%s]
}'

# Create the GeoJSON string by replacing the placeholders with actual values
geojson=$(printf "$geojson_template" "$longitude" "$latitude")

touch "~/pointA.geojson"

# Specify the path to your GeoJSON file
geojson_file="~/pointA.geojson"

# Insert the GeoJSON string into the file
echo "$geojson" > "$geojson_file"

echo "GeoJSON file updated successfully."

