#!/bin/bash

    if [[ ${#1} < 3 ]]; then
         oldformat=1
    fi

     re='^[0-9]+$'
    if [[ $1 =~ $re ]]; then

         is_num=$1
	elif [[ ${#1} < 2 ]]; then

		 num=""
	elif  ! [[ ${1:1:1} =~ $re ]]; then
		 num=""
	else
		 num=${1:1:1}
	fi

	if [ -n "$is_num" ]; then

	    echo "sb-$(padnum $1 4)"
	elif [ -z "$oldformat" ]; then
	    sb_num=$(curl -s https://robot-identities.swarmfarm.com | jq "to_entries[] | select( .value.legacy_name == \"$1\" )" | jq '.key' -r)
	    
	    if [ -z "$sb_num" ]; then
	    
	        echo $1
	    else
	    
	        echo $sb_num
	    fi
	else
	    ascii="$(printf '%d' "'${1:0:1}'")"
	    sb_num=$(( $ascii - 94 ))
	    if [ -n "$num" ]; then
	        sb_num=$(($(( $(($num - 1)) * 26 )) + $sb_num ))
	    fi
	    echo "sb-$(padnum $sb_num 4)"
	fi
